name: Run tests

on:
  push:
    branches:
     - "*"
  pull_request:
    branches:
     - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up --build --exit-code-from web
